import { Bone, CapsuleGeometry, Group, Mesh, MeshStandardMaterial, SphereGeometry, TorusGeometry, Vector3, type Object3D } from 'three';
import type { Motion } from '../core/movement';
import type { CharacterAsset } from '../assets/contract';

const mat = (color: number, roughness = .55, metalness = 0) => new MeshStandardMaterial({ color, roughness, metalness });
const part = (name: string, geometry: CapsuleGeometry | SphereGeometry | TorusGeometry, material: MeshStandardMaterial, position: [number, number, number], scale: [number, number, number]) => { const mesh = new Mesh(geometry, material); mesh.name = name; mesh.position.set(...position); mesh.scale.set(...scale); mesh.castShadow = true; mesh.receiveShadow = true; return mesh; };
const bone = (name: string, position: [number, number, number]) => { const b = new Bone(); b.name = name; b.position.set(...position); return b; };

export class ProceduralRheaAnimation {
  active = 'Idle'; time = 0; private motion: Motion = 'idle';
  constructor(private readonly root: Group, private readonly bones: Record<string, Bone>) {}
  update(motion: Motion, dt: number) { this.motion = motion; this.time += Math.max(0, dt); this.active = motion === 'run' ? 'Run' : motion === 'walk' ? 'Walk' : 'Idle'; const t = this.time; const moving = motion !== 'idle'; const phase = moving ? t * (motion === 'run' ? 10 : 7) : t * 1.7; const swing = moving ? Math.sin(phase) * (motion === 'run' ? .62 : .42) : Math.sin(phase) * .035; const arm = this.bones.LeftUpperArm, armR = this.bones.RightUpperArm, thigh = this.bones.LeftThigh, thighR = this.bones.RightThigh; arm.rotation.x = swing; armR.rotation.x = -swing; thigh.rotation.x = -swing * .7; thighR.rotation.x = swing * .7; this.bones.Hips.position.y = Math.sin(phase * .5) * (moving ? .035 : .012); this.bones.Spine.rotation.z = moving ? Math.sin(phase) * .025 : Math.sin(phase) * .012; this.bones.Head.rotation.z = Math.sin(phase * .45) * .012; }
  get weights() { return { Idle: this.active === 'Idle' ? 1 : 0, Walk: this.active === 'Walk' ? 1 : 0, Run: this.active === 'Run' ? 1 : 0 }; }
  get mixer() { return { time: this.time }; }
  dispose() { this.root.traverse(object => { if (object instanceof Mesh) { object.geometry.dispose(); object.material.dispose(); } }); }
}

export function createProceduralRhea(asset: CharacterAsset) {
  const root = new Group(); root.name = 'RheaProceduralStage1';
  const skin = mat(asset.appearance?.skinColor ?? 0xc88772, .48), outfit = mat(asset.appearance?.outfitColor ?? 0x20222b, .38), accent = mat(asset.appearance?.accentColor ?? 0x7b1428, .35, .15), hair = mat(asset.appearance?.hairColor ?? 0x111217, .62);
  const bones: Record<string, Bone> = {}; const hips = bones.Hips = bone('Hips', [0, .98, 0]); const spine = bones.Spine = bone('Spine', [0, .25, 0]); hips.add(spine); spine.add(bones.Chest = bone('Chest', [0, .35, 0])); spine.add(bones.Neck = bone('Neck', [0, .52, 0])); bones.Neck.add(bones.Head = bone('Head', [0, .18, 0])); root.add(hips);
  bones.Head.add(part('SkullJaw', new SphereGeometry(1, 20, 14), skin, [0, .08, 0], [.24, .29, .22])); bones.Head.add(part('NoseBridge', new CapsuleGeometry(.035, .1, 4, 8), skin, [0, .06, .21], [1, 1, .8])); bones.Head.add(part('EyeLeft', new SphereGeometry(.035, 10, 8), mat(0x17151c, .3), [-.09, .12, .205], [1, 1, .6])); bones.Head.add(part('EyeRight', new SphereGeometry(.035, 10, 8), mat(0x17151c, .3), [.09, .12, .205], [1, 1, .6])); bones.Head.add(part('Brows', new TorusGeometry(.08, .012, 5, 10, Math.PI), hair, [0, .17, .2], [1.2, .55, .5])); bones.Head.add(part('Lips', new CapsuleGeometry(.025, .08, 4, 8), accent, [0, -.02, .21], [1.15, .5, .7]));
  spine.add(part('Ribcage', new CapsuleGeometry(.43, .55, 8, 16), skin, [0, .18, 0], [1.18, 1, .68])); spine.add(part('MatchTop', new CapsuleGeometry(.36, .5, 8, 16), outfit, [0, .21, .22], [1.2, .72, .32])); spine.add(part('TopStrapL', new CapsuleGeometry(.035, .28, 5, 8), accent, [-.24, .4, .23], [1, 1, 1])); spine.add(part('TopStrapR', new CapsuleGeometry(.035, .28, 5, 8), accent, [.24, .4, .23], [1, 1, 1]));
  for (const side of [-1, 1] as const) { const s = side === -1 ? 'Left' : 'Right'; const shoulder = bones[`${s}Shoulder`] = bone(`${s}Shoulder`, [side * .48, .38, 0]); spine.add(shoulder); const ua = bones[`${s}UpperArm`] = bone(`${s}UpperArm`, [side * .22, -.02, 0]); shoulder.add(ua); ua.add(part(`${s}Deltoid`, new SphereGeometry(1, 14, 10), skin, [side * .18, -.03, 0], [.25, .29, .23])); const fore = bones[`${s}Forearm`] = bone(`${s}Forearm`, [side * .38, -.35, 0]); ua.add(fore); fore.add(part(`${s}ForearmMuscle`, new CapsuleGeometry(.14, .3, 7, 12), skin, [side * .04, -.2, .02], [1, 1, 1])); fore.add(part(`${s}Glove`, new CapsuleGeometry(.11, .14, 6, 10), outfit, [0, -.42, .02], [1, .8, 1])); }
  for (const side of [-1, 1] as const) { const s = side === -1 ? 'Left' : 'Right'; const thigh = bones[`${s}Thigh`] = bone(`${s}Thigh`, [side * .2, -.1, 0]); hips.add(thigh); thigh.add(part(`${s}Quad`, new CapsuleGeometry(.2, .48, 8, 12), skin, [0, -.3, 0], [1, 1, .9])); const calf = bones[`${s}Calf`] = bone(`${s}Calf`, [0, -.65, 0]); thigh.add(calf); calf.add(part(`${s}CalfMuscle`, new CapsuleGeometry(.15, .38, 8, 12), skin, [0, -.25, 0], [1, 1, .88])); calf.add(part(`${s}Boot`, new CapsuleGeometry(.17, .3, 8, 12), outfit, [0, -.54, .08], [1.05, .75, 1.35])); }
  hips.add(part('MatchBottoms', new CapsuleGeometry(.42, .25, 8, 14), outfit, [0, -.02, .12], [1.12, .75, .7]));
  for (let i = 0; i < 7; i++) { const strand = part(`HairStrand${i}`, new CapsuleGeometry(.045, .35 + i * .025, 6, 10), hair, [(-.18 + i * .06), .12 - Math.abs(3 - i) * .025, -.08], [1, 1, 1]); bones.Head.add(strand); }
  root.scale.set(asset.scale, asset.scale, asset.scale); const animation = new ProceduralRheaAnimation(root, bones); return { root, animation, stats: { skins: 0, bones: Object.keys(bones).length }, dispose() { animation.dispose(); } };
}
