import { ACESFilmicToneMapping, PerspectiveCamera, WebGLRenderer } from 'three';
import { developmentHumanoid } from '../assets/contract';
import { loadCharacter, disposeObject } from '../character/adapter';
import { createScene } from '../core/scene';
import { createWrestlingRing } from '../match/ring';
import { createArenaWorld } from '../arena/world';
import { EntranceController, type EntranceIdentity } from './system';

export type EntranceSnapshot = { state: string; identity: EntranceIdentity; time: number; event: string; camera: string; loaded: boolean; fps: number };
export class EntranceRuntime {
  private readonly renderer: WebGLRenderer; private readonly camera = new PerspectiveCamera(42, 1, .1, 80); private readonly world = createScene(); private readonly arena = createArenaWorld(); private readonly ring = createWrestlingRing(); private readonly controller: EntranceController; private character?: Awaited<ReturnType<typeof loadCharacter>>; private raf = 0; private last = 0; private frameCount = 0; private sample = 0; private disposed = false;
  constructor(private readonly canvas: HTMLCanvasElement, identity: EntranceIdentity, private readonly stats: (snapshot: EntranceSnapshot) => void, private readonly ready: () => void, private readonly failure: (message: string) => void) { this.controller = new EntranceController(identity); this.controller.start(); this.renderer = new WebGLRenderer({ canvas, antialias: true }); this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 1.5)); this.renderer.shadowMap.enabled = true; this.renderer.toneMapping = ACESFilmicToneMapping; this.world.scene.add(this.arena.arena, this.ring); this.resize(); window.addEventListener('resize', this.resize); void this.load(); this.raf = requestAnimationFrame(this.frame); }
  private async load() { try { this.character = await loadCharacter(developmentHumanoid, new AbortController().signal); if (this.disposed) { this.character.dispose(); return; } this.world.scene.add(this.character.root); this.ready(); } catch (error) { if (!this.disposed) this.failure(error instanceof Error ? error.message : 'Entrance character failed to load.'); } }
  private resize = () => { const w = Math.max(1, this.canvas.clientWidth), h = Math.max(1, this.canvas.clientHeight); this.renderer.setSize(w, h, false); this.camera.aspect = w / h; this.camera.updateProjectionMatrix(); };
  private frame = (now: number) => { if (this.disposed) return; const dt = this.last ? Math.min(.1, (now - this.last) / 1000) : 0; this.last = now; this.controller.tick(dt); if (this.character) { const t = this.controller.time; const z = t < 2.2 ? -17 : t < 5.2 ? -17 + (t - 2.2) * 4.6 : t < 6.2 ? -3.2 : 0; this.character.root.position.set(0, 0, Math.min(0, z)); this.character.root.rotation.y = Math.PI; this.character.animation.update(this.controller.state === 'RAMP' ? 'walk' : 'idle', dt); const anchor = this.controller.event ? this.arena.anchors.get(this.controller.event.camera) : this.arena.anchors.get('stage-hero'); const p = anchor?.position; if (p) { this.camera.position.lerp(p, Math.min(1, dt * 4)); this.camera.lookAt(0, 1.2, Math.min(0, z)); } this.frameCount++; this.sample += dt; if (this.sample >= .25) { this.stats({ state: this.controller.state, identity: this.controller.profile.identity, time: this.controller.time, event: this.controller.event?.presentation ?? '', camera: this.controller.event?.camera ?? 'stage-hero', loaded: true, fps: this.frameCount / this.sample }); this.sample = 0; this.frameCount = 0; } } this.renderer.render(this.world.scene, this.camera); this.raf = requestAnimationFrame(this.frame); };
  skip() { this.controller.skip(); }
  dispose() { if (this.disposed) return; this.disposed = true; cancelAnimationFrame(this.raf); window.removeEventListener('resize', this.resize); if (this.character) { this.world.scene.remove(this.character.root); this.character.dispose(); } disposeObject(this.world.scene); this.renderer.dispose(); }
}
