import { ACESFilmicToneMapping, PerspectiveCamera, WebGLRenderer } from 'three';
import { developmentHumanoid } from '../assets/contract';
import { loadCharacter, disposeObject } from '../character/adapter';
import { createScene } from '../core/scene';
import { createWrestlingRing } from '../match/ring';
import { createArenaWorld } from '../arena/world';
import { EntranceController, type EntranceIdentity } from './system';

export type EntranceSnapshot = { state: string; identity: EntranceIdentity; time: number; event: string; camera: string; loaded: boolean; fps: number };
export class EntranceRuntime {
  private readonly renderer: WebGLRenderer; private readonly camera = new PerspectiveCamera(42, 1, .1, 80); private readonly world = createScene(); private readonly arena = createArenaWorld(); private readonly ring = createWrestlingRing(); private readonly controller: EntranceController; private character?: Awaited<ReturnType<typeof loadCharacter>>; private raf = 0; private last = 0; private frameCount = 0; private sample = 0; private disposed = false; private readonly abort = new AbortController();
  constructor(private readonly canvas: HTMLCanvasElement, identity: EntranceIdentity, private readonly stats: (snapshot: EntranceSnapshot) => void, private readonly ready: () => void, private readonly failure: (message: string) => void) { this.controller = new EntranceController(identity);  this.renderer = new WebGLRenderer({ canvas, antialias: true }); this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 1.5)); this.renderer.shadowMap.enabled = true; this.renderer.toneMapping = ACESFilmicToneMapping; this.world.scene.add(this.arena.arena, this.ring); this.resize(); window.addEventListener('resize', this.resize); void this.load(); this.raf = requestAnimationFrame(this.frame); }
  private async load() { try { this.character = await loadCharacter(developmentHumanoid, this.abort.signal); if (this.disposed) { this.character.dispose(); return; } this.world.scene.add(this.character.root); this.controller.start(); this.ready(); } catch (error) { if (!this.disposed) this.failure(error instanceof Error ? error.message : 'Entrance character failed to load.'); } }
  private resize = () => { const w = Math.max(1, this.canvas.clientWidth), h = Math.max(1, this.canvas.clientHeight); this.renderer.setSize(w, h, false); this.camera.aspect = w / h; this.camera.updateProjectionMatrix(); };
  private frame = (now: number) => { if (this.disposed) return; const dt = this.last ? Math.min(.1, (now - this.last) / 1000) : 0; this.last = now; this.controller.tick(dt); if (this.character) { const terminal = this.controller.state === 'COMPLETE' || this.controller.state === 'SKIPPED'; const events = this.controller.profile.events; const ramp = events.find(e => e.state === 'RAMP')!.time; const ringside = events.find(e => e.state === 'RINGSIDE')!.time; const entry = events.find(e => e.state === 'RING_ENTRY')!.time; const pose = events.find(e => e.state === 'RING_POSE')!.time; const t = this.controller.time; const z = terminal ? 0 : t < ramp ? -17 : t < ringside ? -17 + 12.5 * Math.min(1, (t-ramp)/(ringside-ramp)) : t < entry ? -4.5 : -4.5 + 4.5 * Math.min(1, (t-entry)/(pose-entry)); this.character.root.position.set(0, terminal ? .6 : .6 * Math.max(0, Math.min(1, (t-entry)/(pose-entry))), Math.min(0, z)); this.character.root.rotation.y = Math.PI; this.character.animation.update(this.controller.state === 'RAMP' ? 'walk' : 'idle', dt); const anchor = terminal ? this.arena.anchors.get('hard-camera') : this.controller.event ? this.arena.anchors.get(this.controller.event.camera) : this.arena.anchors.get('stage-hero'); const p = anchor?.position; if (p) { this.camera.position.lerp(p, Math.min(1, dt * 4)); this.camera.lookAt(0, 1.2, Math.min(0, z)); } this.frameCount++; this.sample += dt; if (this.sample >= .25) { this.stats({ state: this.controller.state, identity: this.controller.profile.identity, time: this.controller.time, event: this.controller.event?.presentation ?? '', camera: terminal ? 'hard-camera' : this.controller.event?.camera ?? 'stage-hero', loaded: true, fps: this.frameCount / this.sample }); this.sample = 0; this.frameCount = 0; } } this.renderer.render(this.world.scene, this.camera); this.raf = requestAnimationFrame(this.frame); };
  skip() { this.controller.skip(); }
  dispose() { if (this.disposed) return; this.disposed = true; this.abort.abort(); cancelAnimationFrame(this.raf); window.removeEventListener('resize', this.resize); if (this.character) { this.world.scene.remove(this.character.root); this.character.dispose(); } disposeObject(this.world.scene); this.world.sun.shadow.dispose(); this.renderer.dispose(); }
}
