import {readFileSync} from 'node:fs';
import ts from 'typescript';
import assert from 'node:assert/strict';
const source=readFileSync(new URL('../app/engine.ts',import.meta.url),'utf8');
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {createMatch,attack,step,escapeHold}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const near=()=>{const s=createMatch(0,1,'fight');s.fighters[1].x=440;s.ai=999;return s;};
const run=(s,time)=>{for(let t=0;t<time;t+=.02)step(s,.02,new Set(),()=>.5);};
let s=createMatch(0,1,'fight');attack(s,0,'punch');assert.equal(s.fighters[1].hp,100,'out of range punches must miss');
s=near();attack(s,0,'punch');const hp=s.fighters[1].hp;attack(s,0,'punch');assert.equal(s.fighters[1].hp,hp,'cooldown prevents repeat damage');
s=near();assert.equal(attack(s,0,'finisher'),false,'finisher requires full charge');assert.equal(attack(s,0,'pin'),false,'pin requires knockdown');
s=near();assert.equal(attack(s,0,'suplex'),true);run(s,1.8);assert(s.fighters[1].hp<85);assert(s.fighters[1].down>0);assert.equal(s.hold,null);
s=near();s.fighters[1].hp=9;s.fighters[1].down=5;attack(s,0,'pin');run(s,3.4);assert.equal(s.phase,'over');assert.equal(s.winner,0);assert.match(s.message,/PIN FALL/);
s=near();s.fighters[1].down=5;attack(s,0,'pin');run(s,2);assert.equal(s.phase,'fight');assert.equal(s.hold,null,'healthy opponent kicks out');
s=near();s.fighters[0].down=5;attack(s,1,'pin');for(let i=0;i<8;i++)escapeHold(s,0);step(s,.02,new Set());assert.equal(s.hold,null);assert.equal(s.phase,'fight','player can escape pin');
s=near();s.fighters[1].hp=3;attack(s,0,'submission');run(s,1);assert.equal(s.phase,'over');assert.match(s.message,/SUBMISSION/);
s=near();s.fighters[1].hp=1;attack(s,0,'punch');assert.equal(s.phase,'fight','zero health requires wrestling finish');assert(s.fighters[1].down>0);
s=near();s.phase='paused';const before=s.time;run(s,2);assert.equal(s.time,before,'pause freezes game');
s=near();s.time=.01;step(s,.02,new Set());assert.equal(s.phase,'over');assert.equal(s.winner,null,'equal health at time limit draws');
console.log('11 combat checks passed: range, cooldown, finisher, knockdown, suplex, pin, kickout, escape, submission, pause, time limit.');
