import {readFileSync} from 'node:fs';
import ts from 'typescript';
import assert from 'node:assert/strict';
const source=readFileSync(new URL('../app/engine.ts',import.meta.url),'utf8');
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {createMatch,attack,step,escapeHold,pickupWeapon,skipEntrance,newProfile,buyUpgrade,readProfile}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
let checks=0;const check=(name,fn)=>{fn();checks++;console.log('PASS '+name);};
const near=(a=0,b=1,mode='ring')=>{const s=createMatch(a,b,'fight',mode);s.fighters[1].x=440;s.ai=999;return s;};
const run=(s,time)=>{for(let t=0;t<time;t+=.02)step(s,.02,new Set(),()=>.5);};
check('out-of-range punches miss',()=>{const s=createMatch(0,1,'fight');attack(s,0,'punch');assert.equal(s.fighters[1].hp,s.fighters[1].maxHp);});
check('cooldown prevents duplicate damage',()=>{const s=near();attack(s,0,'punch');const hp=s.fighters[1].hp;attack(s,0,'punch');assert.equal(s.fighters[1].hp,hp);});
check('finisher and pin requirements',()=>{const s=near();assert.equal(attack(s,0,'finisher'),false);assert.equal(attack(s,0,'pin'),false);});
check('suplex applies one delayed impact and knockdown',()=>{const s=near();attack(s,0,'suplex');assert.equal(s.fighters[1].hp,s.fighters[1].maxHp);run(s,1.8);assert(s.fighters[1].hp<s.fighters[1].maxHp-15);assert(s.fighters[1].down>0);assert.equal(s.impact,1);});
check('weak opponent can be pinned for three',()=>{const s=near();s.fighters[1].hp=9;s.fighters[1].down=5;attack(s,0,'pin');run(s,3.4);assert.equal(s.phase,'over');assert.equal(s.winner,0);assert.match(s.message,/PIN FALL/);});
check('healthy CPU kicks out',()=>{const s=near();s.fighters[1].down=5;attack(s,0,'pin');run(s,2);assert.equal(s.phase,'fight');assert.equal(s.hold,null);});
check('player can escape holds',()=>{const s=near();s.fighters[0].down=5;attack(s,1,'pin');for(let i=0;i<8;i++)escapeHold(s,0);step(s,.02,new Set());assert.equal(s.hold,null);assert.equal(s.phase,'fight');});
check('submission wins by tapout',()=>{const s=near();s.fighters[1].hp=3;attack(s,0,'submission');run(s,1);assert.equal(s.phase,'over');assert.match(s.message,/SUBMISSION/);});
check('zero health in ring requires a wrestling finish',()=>{const s=near();s.fighters[1].hp=1;attack(s,0,'punch');assert.equal(s.phase,'fight');assert(s.fighters[1].down>0);});
check('pause freezes timer and holds',()=>{const s=near();attack(s,0,'suplex');s.phase='paused';const before=s.time;run(s,2);assert.equal(s.time,before);assert.equal(s.hold.time,0);});
check('time limit uses health correctly',()=>{const s=near();s.fighters[1].hp=s.fighters[0].hp;s.time=.01;step(s,.02,new Set());assert.equal(s.phase,'over');assert.equal(s.winner,null);});
check('Chyna is stronger and uniquely performs press slam',()=>{const s=near(1,0);assert(s.fighters[0].power>s.fighters[1].power);assert(s.fighters[0].maxHp>s.fighters[1].maxHp);assert(attack(s,0,'press'));run(s,2.9);assert(s.fighters[1].hp<65);assert(s.fighters[1].down>0);assert(!attack(near(0,1),0,'press'));});
check('weapon pickups require mode and proximity',()=>{const s=near(0,1,'extreme');assert(!pickupWeapon(s,0));s.fighters[0].x=220;s.fighters[0].y=418;assert(pickupWeapon(s,0));assert.equal(s.fighters[0].weapon,'chair');assert(s.pickups[0].taken);assert(!pickupWeapon(near(),0));});
check('weapon durability exhausts and weapon hits knock down',()=>{const s=near(0,1,'extreme');s.fighters[0].weapon='chair';s.fighters[0].durability=1;attack(s,0,'weapon');assert.equal(s.fighters[0].weapon,null);assert(s.fighters[1].down>0);});
check('backstage wins by KO and rejects pins',()=>{const s=near(0,1,'backstage');s.fighters[1].down=3;assert(!attack(s,0,'pin'));s.fighters[1].down=0;s.fighters[1].hp=1;attack(s,0,'punch');assert.equal(s.phase,'over');assert.match(s.message,/BACKSTAGE KO/);});
check('power toss can break a table once',()=>{const s=near(1,0,'backstage');s.fighters[0].x=710;s.fighters[1].x=810;attack(s,0,'toss');run(s,1.4);assert(s.tableBroken);assert(s.fighters[1].hp<65);});
check('entrance transitions and can be skipped',()=>{const s=createMatch(1,0,'entrance');run(s,8.2);assert.equal(s.phase,'fight');const t=createMatch(1,0,'entrance');skipEntrance(t);assert.equal(t.phase,'fight');});
check('upgrades deduct correct price, persist and affect stats',()=>{let p=newProfile();p=buyUpgrade(p,1,'power');assert.equal(p.points,5);assert.equal(p.upgrades[1].power,1);p=buyUpgrade(p,1,'power');assert.equal(p.points,3);const restored=readProfile(JSON.parse(JSON.stringify(p)));const s=createMatch(1,0,'fight','ring',restored.upgrades[1]);assert(s.fighters[0].power>130);assert.equal(buyUpgrade({...p,points:0},1,'power'),null);});
check('upgrade cap and corrupted saves are bounded',()=>{let p=newProfile();p.points=100;for(let i=0;i<5;i++)p=buyUpgrade(p,0,'toughness');assert.equal(buyUpgrade(p,0,'toughness'),null);assert.equal(readProfile({points:-5,upgrades:[{power:999,toughness:-3,speed:NaN}]}).upgrades[0].power,5);assert.equal(readProfile(null).points,6);});
check('stamina prevents unlimited heavy attacks',()=>{const s=near(1,0);s.fighters[0].stamina=0;assert(!attack(s,0,'press'));run(s,3);assert(s.fighters[0].stamina>25);});
console.log(`${checks} combat and progression checks passed.`);
