import { ACESFilmicToneMapping, PerspectiveCamera, WebGLRenderer } from 'three';
import { developmentHumanoid } from '../assets/contract';
import { loadCharacter, disposeObject } from '../character/adapter';
import { createScene } from '../core/scene';
import { KeyboardInput } from '../input/keyboard';
import { FollowCamera } from '../camera/follow';
import { createBackstageWorld, BackstageNavigator } from './world';
export type BackstageSnapshot = { x: number; z: number; yaw: number; zone: string; prompt: string; interaction: string; fps: number; loaded: boolean };
export class BackstageRuntime { private readonly renderer: WebGLRenderer; private readonly camera = new PerspectiveCamera(42, 1, .1, 80); private readonly world = createScene(); private readonly backstage = createBackstageWorld(); private readonly nav = new BackstageNavigator(); private readonly input: KeyboardInput; private readonly follow: FollowCamera; private character?: Awaited<ReturnType<typeof loadCharacter>>; private raf = 0; private last = 0; private sample = 0; private frames = 0; private disposed = false; private readonly abort = new AbortController(); private interaction = ''; private interact = (event: KeyboardEvent) => { if (event.code === 'KeyE') this.interaction = this.nav.interact() ?? ''; };
  constructor(private readonly canvas: HTMLCanvasElement, private readonly stats: (s: BackstageSnapshot) => void, private readonly ready: () => void, private readonly failure: (m: string) => void) { this.renderer = new WebGLRenderer({ canvas, antialias: true }); this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 1.5)); this.renderer.shadowMap.enabled = true; this.renderer.toneMapping = ACESFilmicToneMapping; this.world.scene.add(this.backstage); this.input = new KeyboardInput(window, document); this.follow = new FollowCamera(this.camera, canvas); canvas.addEventListener('webglcontextlost', this.contextLost); window.addEventListener('keydown', this.interact); this.resize(); window.addEventListener('resize', this.resize); void this.load(); this.raf = requestAnimationFrame(this.frame); }
  private contextLost = (event: Event) => { event.preventDefault(); cancelAnimationFrame(this.raf); this.input.clear(); this.failure('Backstage WebGL context lost. Reload to recover.'); };
  private async load() { try { this.character = await loadCharacter(developmentHumanoid, this.abort.signal); if (this.disposed) { this.character.dispose(); return; } this.world.scene.add(this.character.root); this.ready(); } catch (error) { if (!this.disposed) this.failure(error instanceof Error ? error.message : 'Backstage player failed to load.'); } }
  private resize = () => { const w = Math.max(1, this.canvas.clientWidth), h = Math.max(1, this.canvas.clientHeight); this.renderer.setSize(w, h, false); this.camera.aspect = w / h; this.camera.updateProjectionMatrix(); };
  private frame = (now: number) => { if (this.disposed) return; const dt = this.last ? Math.min(.1, (now - this.last) / 1000) : 0; this.last = now; const intent = this.input.intent; this.nav.move(intent.x, intent.z, dt * (intent.run ? 1.55 : 1)); if (this.character) { this.character.root.position.set(this.nav.x, 0, this.nav.z); this.character.root.rotation.y = this.nav.yaw; this.character.animation.update(intent.x || intent.z ? intent.run ? 'run' : 'walk' : 'idle', dt); this.follow.update(this.character.root.position, dt); this.sample += dt; this.frames++; if (this.sample >= .25) { const nearest = this.nav.nearestInteraction(); this.stats({ x: this.nav.x, z: this.nav.z, yaw: this.nav.yaw, zone: this.nav.zone, prompt: nearest?.prompt ?? '', interaction: this.interaction, fps: this.frames / this.sample, loaded: true }); this.sample = 0; this.frames = 0; } } this.renderer.render(this.world.scene, this.camera); this.raf = requestAnimationFrame(this.frame); };
  dispose() { if (this.disposed) return; this.disposed = true; this.abort.abort(); cancelAnimationFrame(this.raf); this.input.dispose(); this.follow.dispose(); window.removeEventListener('keydown', this.interact); window.removeEventListener('resize', this.resize); this.canvas.removeEventListener('webglcontextlost', this.contextLost); if (this.character) { this.world.scene.remove(this.character.root); this.character.dispose(); } disposeObject(this.world.scene); this.world.sun.shadow.dispose(); this.renderer.dispose(); }
}
