import { BoxGeometry, Group, Mesh, MeshStandardMaterial } from 'three';
export type BackstageZoneId = 'MAIN_CORRIDOR' | 'RHEA_LOCKER' | 'CHYNA_LOCKER' | 'CHARLOTTE_LOCKER' | 'BIANCA_LOCKER' | 'INTERVIEW_AREA' | 'MANAGER_OFFICE' | 'LOADING_BAY' | 'ARENA_ACCESS';
export type BackstageZone = { id: BackstageZoneId; bounds: { minX: number; maxX: number; minZ: number; maxZ: number }; color: string };
export type Interactable = { id: string; type: 'door' | 'marker' | 'access'; zone: BackstageZoneId; x: number; z: number; range: number; prompt: string };
export const backstageZones: BackstageZone[] = [
  { id: 'MAIN_CORRIDOR', bounds: { minX: -3, maxX: 3, minZ: -14, maxZ: 14 }, color: '#283441' }, { id: 'RHEA_LOCKER', bounds: { minX: -10, maxX: -3, minZ: 8, maxZ: 14 }, color: '#352537' }, { id: 'CHYNA_LOCKER', bounds: { minX: 3, maxX: 10, minZ: 8, maxZ: 14 }, color: '#453023' }, { id: 'CHARLOTTE_LOCKER', bounds: { minX: -10, maxX: -3, minZ: -14, maxZ: -8 }, color: '#263747' }, { id: 'BIANCA_LOCKER', bounds: { minX: 3, maxX: 10, minZ: -14, maxZ: -8 }, color: '#243c36' }, { id: 'INTERVIEW_AREA', bounds: { minX: -8, maxX: 8, minZ: 3, maxZ: 7 }, color: '#3c2947' }, { id: 'MANAGER_OFFICE', bounds: { minX: -10, maxX: -3, minZ: -6, maxZ: 0 }, color: '#39382a' }, { id: 'LOADING_BAY', bounds: { minX: 3, maxX: 10, minZ: -6, maxZ: 0 }, color: '#333b42' }, { id: 'ARENA_ACCESS', bounds: { minX: -2, maxX: 2, minZ: 14, maxZ: 18 }, color: '#463254' },
];
export const interactables: Interactable[] = [{ id: 'door-rhea', type: 'door', zone: 'RHEA_LOCKER', x: -3.1, z: 11, range: 1.8, prompt: 'E · ENTER RHEA LOCKER' }, { id: 'door-chyna', type: 'door', zone: 'CHYNA_LOCKER', x: 3.1, z: 11, range: 1.8, prompt: 'E · ENTER CHYNA LOCKER' }, { id: 'door-charlotte', type: 'door', zone: 'CHARLOTTE_LOCKER', x: -3.1, z: -11, range: 1.8, prompt: 'E · ENTER CHARLOTTE LOCKER' }, { id: 'door-bianca', type: 'door', zone: 'BIANCA_LOCKER', x: 3.1, z: -11, range: 1.8, prompt: 'E · ENTER BIANCA LOCKER' }, { id: 'interview-marker', type: 'marker', zone: 'INTERVIEW_AREA', x: 0, z: 5, range: 2, prompt: 'E · INTERVIEW MARKER' }, { id: 'manager-marker', type: 'marker', zone: 'MANAGER_OFFICE', x: -6, z: -3, range: 2, prompt: 'E · MANAGER OFFICE ANCHOR' }, { id: 'loading-marker', type: 'marker', zone: 'LOADING_BAY', x: 6, z: -3, range: 2, prompt: 'E · LOADING BAY ANCHOR' }, { id: 'arena-access', type: 'access', zone: 'ARENA_ACCESS', x: 0, z: 16, range: 2, prompt: 'E · ARENA ACCESS' }];
const inside = (zone: BackstageZone, x: number, z: number) => x >= zone.bounds.minX && x <= zone.bounds.maxX && z >= zone.bounds.minZ && z <= zone.bounds.maxZ;
export class BackstageNavigator { x = 0; z = -12; yaw = 0; get zone() { return [...backstageZones].sort((a, b) => Number(a.id === 'MAIN_CORRIDOR') - Number(b.id === 'MAIN_CORRIDOR')).find(item => inside(item, this.x, this.z))?.id ?? 'MAIN_CORRIDOR'; } move(dx: number, dz: number, dt: number) { const speed = 4 * dt; const nx = Math.max(-11.2, Math.min(11.2, this.x + dx * speed)); const nz = Math.max(-17.2, Math.min(17.2, this.z + dz * speed)); this.x = nx; this.z = nz; if (Math.abs(dx) + Math.abs(dz) > .01) this.yaw = Math.atan2(dx, dz); } nearestInteraction() { let best: Interactable | undefined; let distance = Infinity; for (const item of interactables) { const d = Math.hypot(item.x - this.x, item.z - this.z); if (d <= item.range && d < distance) { best = item; distance = d; } } return best; } interact() { return this.nearestInteraction()?.id ?? null; }
}
const block = (name: string, size: [number, number, number], x: number, y: number, z: number, color: string) => { const mesh = new Mesh(new BoxGeometry(...size), new MeshStandardMaterial({ color, roughness: .85 })); mesh.name = name; mesh.position.set(x, y, z); mesh.castShadow = true; mesh.receiveShadow = true; return mesh; };
export function createBackstageWorld() { const group = new Group(); group.name = 'BackstageHubPhase7'; group.add(block('BackstageFloor', [24, .2, 36], 0, -.1, 0, '#202a32')); for (const zone of backstageZones) { const x = (zone.bounds.minX + zone.bounds.maxX) / 2, z = (zone.bounds.minZ + zone.bounds.maxZ) / 2; if (zone.id !== 'MAIN_CORRIDOR') group.add(block(`ZoneFloor:${zone.id}`, [zone.bounds.maxX - zone.bounds.minX, .05, zone.bounds.maxZ - zone.bounds.minZ], x, .02, z, zone.color)); } for (const x of [-12, 12]) group.add(block('BackstageWall', [.3, 3.2, 36], x, 1.6, 0, '#151c24')); for (const z of [-18, 18]) group.add(block('BackstageWall', [24, 3.2, .3], 0, 1.6, z, '#151c24')); for (const item of interactables) { group.add(block(`Interactable:${item.id}`, [.35, 1.8, .15], item.x, .9, item.z, item.type === 'door' ? '#8c6ab0' : '#d3a85e')); } group.add(block('InterviewBackdrop', [7, 3, .2], 0, 1.5, 7, '#583e73'), block('ManagerDesk', [3.2, 1, 1.2], -6, .5, -3.8, '#4f4432'), block('LoadingBayCrate', [2, 2, 2], 7, 1, -4, '#4e5961')); return group; }
