import {type Match,roster} from './engine';
/** Original synthesized arena audio and optional device narrator. No copied music or cloned voices. */
export class ArenaAudio{
 private ctx:AudioContext|null=null;private master:GainNode|null=null;private crowd:AudioBufferSourceNode|null=null;private crowdGain:GainNode|null=null;private timer:ReturnType<typeof setInterval>|null=null;private beat=0;private scene='select';private character=0;private previous='';private lastImpact=0;private hold='';private entrant=-1;private spokenAt=0;
 enabled=true;voiceEnabled=true;
 activate(){try{this.ctx??=new AudioContext();void this.ctx.resume();if(!this.master){this.master=this.ctx.createGain();this.master.gain.value=this.enabled?.28:0;const compressor=this.ctx.createDynamicsCompressor();this.master.connect(compressor);compressor.connect(this.ctx.destination);const buffer=this.ctx.createBuffer(1,this.ctx.sampleRate*2,this.ctx.sampleRate),d=buffer.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*.5;this.crowd=this.ctx.createBufferSource();this.crowd.buffer=buffer;this.crowd.loop=true;const filter=this.ctx.createBiquadFilter();filter.type='bandpass';filter.frequency.value=700;filter.Q.value=.65;this.crowdGain=this.ctx.createGain();this.crowdGain.gain.value=0;this.crowd.connect(filter);filter.connect(this.crowdGain);this.crowdGain.connect(this.master);this.crowd.start();}if(!this.timer)this.timer=setInterval(()=>this.music(),250);}catch{}}
 setEnabled(v:boolean){this.enabled=v;if(this.master&&this.ctx)this.master.gain.setTargetAtTime(v?.28:0,this.ctx.currentTime,.1);if(!v&&typeof speechSynthesis!=='undefined')speechSynthesis.cancel();}
 setVoice(v:boolean){this.voiceEnabled=v;if(!v&&typeof speechSynthesis!=='undefined')speechSynthesis.cancel();}
 private note(freq:number,duration:number,volume=.12,type:OscillatorType='sine'){if(!this.enabled||!this.ctx||!this.master)return;const c=this.ctx,o=c.createOscillator(),g=c.createGain(),filter=c.createBiquadFilter();o.type=type;o.frequency.value=freq;filter.type='lowpass';filter.frequency.value=1400;o.connect(filter);filter.connect(g);g.connect(this.master);g.gain.setValueAtTime(volume,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);o.start();o.stop(c.currentTime+duration+.01);}
 effect(freq=130){this.note(freq,.16,.32,'triangle');this.note(freq*.52,.22,.2,'sine');}
 private music(){if(!this.enabled||!['entrance','fight'].includes(this.scene))return;this.beat++;const roots=[65.4,55,82.4,73.4],base=roots[this.character];if(this.scene==='entrance'){const riff=[1,1,1.5,1.335,1,2,1.5,1.19];this.note(base*riff[this.beat%8],.22,.17,'sawtooth');if(this.beat%2===0)this.note(46,.12,.4);if(this.beat%8===0)this.note(base*4,.7,.08,'triangle');}else if(this.beat%4===0)this.note(42,.13,.11);if(this.crowdGain&&this.ctx){const volume=this.scene==='entrance'?.07:.04+Math.sin(this.beat*.45)*.012;this.crowdGain.gain.setTargetAtTime(volume,this.ctx.currentTime,.2);}}
 say(text:string,force=false){if(!this.enabled||!this.voiceEnabled||typeof speechSynthesis==='undefined')return;const now=Date.now();if(!force&&now-this.spokenAt<2800)return;this.spokenAt=now;try{speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);const voices=speechSynthesis.getVoices();utterance.voice=voices.find(v=>v.lang==='en-IN')??voices.find(v=>v.lang.startsWith('en'))??null;utterance.lang=utterance.voice?.lang??'en-US';utterance.rate=1.02;utterance.pitch=.88;utterance.volume=.85;speechSynthesis.speak(utterance);}catch{}}
 observe(s:Match){this.scene=s.phase;this.character=s.fighters[0].id;if(s.phase!==this.previous){this.previous=s.phase;this.hold='';if(s.phase==='fight'){this.say(s.mode==='backstage'?'Trouble backstage! No disqualifications. Anything can happen.':'The bell rings! Here we go!',true);this.effect(650);}if(s.phase==='over'){const name=s.winner===null?'This match is a draw':`${roster[s.fighters[s.winner].id].name} wins`;this.say(name+'. What a performance!',true);this.note(330,.4);this.note(440,.7);this.note(550,1);}if(!['fight','entrance'].includes(s.phase)&&this.crowdGain&&this.ctx)this.crowdGain.gain.setTargetAtTime(0,this.ctx.currentTime,.2);if(s.phase==='paused'&&typeof speechSynthesis!=='undefined')speechSynthesis.cancel();}
 if(s.phase==='entrance'){const entrant=s.entranceTime<4?0:1;this.character=s.fighters[entrant].id;if(entrant!==this.entrant){this.entrant=entrant;this.character=s.fighters[entrant].id;this.say(`Making her way to the ring. ${roster[this.character].name}. ${roster[this.character].title}.`,true);}return;}this.entrant=-1;
 if(s.phase!=='fight')return;const kind=s.hold?.kind??'';if(kind!==this.hold){this.hold=kind;if(kind){const name=roster[s.fighters[s.hold!.attacker].id].name;const words:Record<string,string>={press:`${name} powers her overhead! Gorilla press slam!`,finisher:`${name} has the finish! ${roster[s.fighters[s.hold!.attacker].id].finisher}!`,suplex:'Hooks the grip. Big vertical suplex!',submission:'Submission locked in! Can she escape?',pin:'The cover! One! Two!',toss:'Sends her flying!',ambush:'From behind! A vicious sneak attack!'};this.say(words[kind]??'What a move!');}}
 if(s.impact!==this.lastImpact){this.lastImpact=s.impact;this.effect(s.hold?85:145);if(s.tableBroken)this.say('Right through the table! Unbelievable!');else if(s.message.includes('WALL'))this.say('Driven into the wall!');else if(s.fighters.some(f=>f.hp/f.maxHp<.2))this.say('She is in serious trouble now!');}
 if(s.message.includes('VILLAIN'))this.say('Look at the disrespect! The crowd does not like that!');}
 dispose(){if(this.timer)clearInterval(this.timer);this.timer=null;this.crowd?.stop();if(this.ctx)void this.ctx.close();if(typeof speechSynthesis!=='undefined')speechSynthesis.cancel();}
}
