export const roster=[{name:'RHEA',title:'THE NIGHTMARE',color:'#ba94ff',power:94,speed:78,finisher:'RIPTIDE'},{name:'CHYNA',title:'THE NINTH WONDER',color:'#f47564',power:112,speed:70,finisher:'PEDIGREE'},{name:'CHARLOTTE',title:'THE QUEEN',color:'#7edbff',power:86,speed:87,finisher:'NATURAL SELECTION'},{name:'BIANCA',title:'THE EST',color:'#edc558',power:91,speed:95,finisher:'K.O.D.'}];
export type Action='idle'|'walk'|'punch'|'kick'|'block'|'hit'|'suplex'|'submission'|'pin'|'finisher'|'down'|'press'|'toss'|'weapon'|'taunt';
export type Mode='ring'|'extreme'|'backstage';
export type Weapon='chair'|'kendo'|'hammer';
export type Upgrades={power:number,toughness:number,speed:number};
export type Profile={points:number,wins:number,losses:number,upgrades:Upgrades[]};
export const newProfile=():Profile=>({points:6,wins:0,losses:0,upgrades:Array.from({length:4},()=>({power:0,toughness:0,speed:0}))});
export function readProfile(raw:unknown):Profile{const d=raw as Partial<Profile>|null,p=newProfile();if(!d||typeof d!=='object')return p;const integer=(v:unknown,max:number)=>typeof v==='number'&&Number.isFinite(v)?Math.max(0,Math.min(max,Math.floor(v))):0;p.points=integer(d.points,9999);p.wins=integer(d.wins,99999);p.losses=integer(d.losses,99999);if(Array.isArray(d.upgrades))for(let i=0;i<4;i++){const u=d.upgrades[i];if(u&&typeof u==='object')p.upgrades[i]={power:integer(u.power,5),toughness:integer(u.toughness,5),speed:integer(u.speed,5)};}return p;}
export function buyUpgrade(p:Profile,id:number,kind:keyof Upgrades):Profile|null{if(!Number.isInteger(id)||id<0||id>3||!['power','toughness','speed'].includes(kind))return null;const level=p.upgrades[id][kind],cost=level+1;if(level>=5||p.points<cost)return null;return {...p,points:p.points-cost,upgrades:p.upgrades.map((u,i)=>i===id?{...u,[kind]:level+1}:{...u})};}
export type Fighter={id:number,x:number,y:number,hp:number,maxHp:number,power:number,speed:number,energy:number,stamina:number,cooldown:number,action:Action,anim:number,duration:number,face:number,down:number,weapon:Weapon|null,durability:number};
export type Hold={kind:'suplex'|'submission'|'pin'|'finisher'|'press'|'toss',attacker:0|1,time:number,duration:number,escape:number,damageApplied:boolean};
export type Pickup={kind:Weapon,x:number,y:number,taken:boolean};
export type Match={fighters:[Fighter,Fighter],phase:'select'|'entrance'|'fight'|'paused'|'over',mode:Mode,time:number,ai:number,hold:Hold|null,message:string,messageTime:number,shake:number,impact:number,winner:number|null,entranceTime:number,pickups:Pickup[],tableBroken:boolean,earned:boolean};
export const makeFighter=(id:number,x:number,u:Upgrades={power:0,toughness:0,speed:0}):Fighter=>{const maxHp=(id===1?115:100)+u.toughness*10;return {id,x,y:382,hp:maxHp,maxHp,power:roster[id].power*(1+u.power*.09),speed:roster[id].speed*(1+u.speed*.06),energy:0,stamina:100,cooldown:0,action:'idle',anim:0,duration:0,face:x<500?1:-1,down:0,weapon:null,durability:0};};
export const createMatch=(a=0,b=1,phase:Match['phase']='select',mode:Mode='ring',upgrades:Upgrades={power:0,toughness:0,speed:0}):Match=>({fighters:[makeFighter(a,350,upgrades),makeFighter(b,690)],phase,mode,time:180,ai:.8,hold:null,message:mode==='backstage'?'BACKSTAGE BRAWL':'BELL RINGS',messageTime:1.2,shake:0,impact:0,winner:null,entranceTime:0,pickups:mode==='ring'?[]:[{kind:'chair',x:220,y:418,taken:false},{kind:'kendo',x:520,y:440,taken:false},{kind:'hammer',x:820,y:405,taken:false}],tableBroken:false,earned:false});
const distance=(a:{x:number,y:number},b:{x:number,y:number})=>Math.hypot(a.x-b.x,(a.y-b.y)*1.5);
const announce=(s:Match,message:string,time=1)=>{s.message=message;s.messageTime=time;};
const finish=(s:Match,winner:number|null,reason:string)=>{s.phase='over';s.winner=winner;announce(s,winner===null?'DRAW':`${roster[s.fighters[winner].id].name} WINS`,99);s.message+=` · ${reason}`;s.hold=null;};
const hurt=(s:Match,a:Fighter,b:Fighter,n:number)=>{b.hp=Math.max(0,b.hp-n);a.energy=Math.min(100,a.energy+12);b.energy=Math.min(100,b.energy+5);s.shake=.18;s.impact++;};
export function skipEntrance(s:Match){if(s.phase==='entrance'){s.phase='fight';s.entranceTime=0;announce(s,s.mode==='backstage'?'BACKSTAGE BRAWL':'BELL RINGS');}}
export function escapeHold(s:Match,who:number){if(s.phase==='fight'&&s.hold&&who!==s.hold.attacker&&['submission','pin'].includes(s.hold.kind))s.hold.escape=Math.min(1,s.hold.escape+.13);}
export function pickupWeapon(s:Match,who:0|1){if(s.phase!=='fight'||s.mode==='ring'||s.hold)return false;const a=s.fighters[who];if(a.down||a.cooldown)return false;if(a.weapon){s.pickups.push({kind:a.weapon,x:a.x,y:a.y,taken:false});a.weapon=null;a.durability=0;return true;}const item=s.pickups.find(p=>!p.taken&&distance(a,p)<86);if(!item){announce(s,'STAND NEAR A WEAPON · F TO PICK UP');return false;}item.taken=true;a.weapon=item.kind;a.durability=item.kind==='hammer'?4:item.kind==='chair'?3:5;announce(s,`${item.kind.toUpperCase()} EQUIPPED · H TO SWING`);return true;}
export function attack(s:Match,who:0|1,kind:Action){const a=s.fighters[who],b=s.fighters[1-who];if(s.phase!=='fight'||s.hold||a.cooldown>0||a.down>0)return false;
if(kind==='taunt'){a.energy=Math.min(100,a.energy+8);a.cooldown=1.5;a.action='taunt';a.anim=1.5;a.duration=1.5;announce(s,'CROWD MOMENTUM +8');return true;}
const ground=b.down>0,range=kind==='weapon'?170:kind==='kick'?148:kind==='punch'?132:118,cost=kind==='weapon'?19:['press','suplex','toss'].includes(kind)?25:kind==='kick'?12:kind==='punch'?6:0;
if(a.stamina<cost){announce(s,'LOW STAMINA · RECOVER');return false;}
if(kind==='press'&&a.id!==1){announce(s,'GORILLA PRESS IS CHYNA’S SIGNATURE');return false;}
if(kind==='weapon'&&!a.weapon){announce(s,'PICK UP A WEAPON FIRST · F');return false;}
if(kind==='finisher'&&a.energy<100){announce(s,'CHARGE YOUR FINISHER FIRST');return false;}
if(kind==='pin'&&s.mode==='backstage'){announce(s,'BACKSTAGE: WIN BY KO OR SUBMISSION');return false;}
if(kind==='pin'&&!ground){announce(s,'KNOCK THEM DOWN, THEN PIN');return false;}
if(['suplex','submission','pin','finisher','press','toss'].includes(kind)&&distance(a,b)>range){announce(s,'GET CLOSER TO GRAPPLE');a.cooldown=.25;return false;}
if(['punch','kick'].includes(kind)&&ground){announce(s,s.mode==='backstage'?'OPPONENT DOWN · SUBMIT OR USE A WEAPON':'OPPONENT DOWN · PIN OR SUBMIT');return false;}
if(['suplex','submission','pin','finisher','press','toss'].includes(kind)){
if(ground&&['suplex','finisher','press','toss'].includes(kind)){announce(s,'OPPONENT DOWN · PIN OR SUBMIT');return false;}
const duration=kind==='suplex'?1.65:kind==='press'?2.7:kind==='toss'?1.2:kind==='finisher'?2.2:kind==='pin'?3.2:4;
s.hold={kind:kind as Hold['kind'],attacker:who,time:0,duration,escape:0,damageApplied:false};a.stamina-=cost;a.action=kind;a.duration=duration;a.anim=duration;b.action=kind==='pin'?'down':'hit';b.anim=duration;a.face=b.x>=a.x?1:-1;b.face=-a.face;if(kind==='finisher')a.energy=0;
announce(s,kind==='finisher'?roster[a.id].finisher:kind==='press'?'GORILLA PRESS SLAM':kind==='toss'?'POWER TOSS':kind==='suplex'?'VERTICAL SUPLEX':kind==='submission'?'SUBMISSION LOCKED':'COVER!',duration);return true;}
a.stamina-=cost;a.action=kind;a.anim=kind==='weapon'?.65:kind==='kick'?.48:.32;a.duration=a.anim;a.cooldown=kind==='weapon'?.95:kind==='kick'?.68:.4;
const weaponDamage=a.weapon==='hammer'?25:a.weapon==='chair'?19:14;if(kind==='weapon'){a.durability--;if(a.durability===0)announce(s,'WEAPON BREAKS AFTER THIS SWING');}
if(distance(a,b)<=range){const blocked=b.action==='block';hurt(s,a,b,(kind==='weapon'?weaponDamage:kind==='kick'?10:6)*a.power/90*(blocked?.2:1));if(blocked)announce(s,'BLOCKED',.5);else{b.action='hit';b.anim=.25;b.duration=.25;b.cooldown=.25;b.x+=a.face*(kind==='weapon'?25:10);if(b.hp<=0||kind==='weapon'){b.down=kind==='weapon'?2.1:5;b.action='down';if(b.hp<=0)announce(s,'DOWN! PIN OR SUBMIT TO WIN',2);}}}if(kind==='weapon'&&a.durability<=0){a.weapon=null;a.durability=0;}if(s.mode==='backstage'&&b.hp<=0)finish(s,who,'BACKSTAGE KO');return true;}
export function step(s:Match,dt:number,keys:Set<string>,random=Math.random){dt=Math.min(dt,.04);if(s.phase==='entrance'){s.entranceTime+=dt;if(s.entranceTime>=8)skipEntrance(s);return;}if(s.phase!=='fight')return;s.time=Math.max(0,s.time-dt);s.messageTime=Math.max(0,s.messageTime-dt);s.shake=Math.max(0,s.shake-dt);const [p,e]=s.fighters;for(const f of s.fighters)f.stamina=Math.min(100,f.stamina+dt*(f.action==='block'?7:11));
if(s.hold){const h=s.hold,a=s.fighters[h.attacker],b=s.fighters[1-h.attacker];h.time+=dt;if(h.kind==='submission'||h.kind==='pin'){if(h.attacker===0)h.escape+=dt*(h.kind==='pin'?(b.hp/b.maxHp>.35?.65:b.hp/b.maxHp>.15?.26:.07):.13+(b.hp/b.maxHp)*.3);if(h.escape>=1){b.down=.8;a.cooldown=.8;announce(s,'ESCAPED!',1.2);s.hold=null;}else if(h.kind==='submission'){b.hp=Math.max(0,b.hp-dt*5*a.power/90);if(b.hp<=0)finish(s,h.attacker,'SUBMISSION');}else if(h.time>=h.duration)finish(s,h.attacker,'PIN FALL');}
if(s.hold&&['suplex','finisher','press','toss'].includes(h.kind)&&h.time>h.duration*.74&&!h.damageApplied){const base=h.kind==='suplex'?18:h.kind==='press'?29:h.kind==='toss'?17:38;hurt(s,a,b,base*a.power/90);h.damageApplied=true;s.shake=.38;b.down=h.kind==='press'?6:5;if(h.kind==='toss'){b.x=Math.max(170,Math.min(870,a.x+a.face*175));if(s.mode==='backstage'&&(b.x<225||b.x>810)){hurt(s,a,b,10);announce(s,'WALL IMPACT!',1.5);}if(s.mode!=='ring'&&!s.tableBroken&&b.x>710){s.tableBroken=true;hurt(s,a,b,12);announce(s,'THROUGH THE TABLE!',1.5);}}if(s.mode==='backstage'&&b.hp<=0)finish(s,h.attacker,'BACKSTAGE KO');}
if(s.hold&&h.time>=h.duration){b.down=Math.max(b.down,1.2);a.cooldown=.5;s.hold=null;announce(s,s.mode==='backstage'?'KEEP THE PRESSURE ON':b.hp<=0?'PIN OR SUBMIT TO FINISH':'OPPONENT DOWN · N TO PIN',1.5);}
if(!s.hold)for(const f of s.fighters){f.anim=0;f.action=f.down>0?'down':'idle';}
}else{
for(const f of s.fighters){f.cooldown=Math.max(0,f.cooldown-dt);f.anim=Math.max(0,f.anim-dt);f.down=Math.max(0,f.down-dt);if(f.down>0)f.action='down';else if(f.anim===0)f.action='idle';}p.face=e.x>=p.x?1:-1;e.face=-p.face;
const blocking=keys.has(' ')&&p.cooldown===0&&p.down===0;if(blocking)p.action='block';if(p.cooldown===0&&p.down===0&&!blocking){const dx=+(keys.has('d')||keys.has('arrowright'))-+(keys.has('a')||keys.has('arrowleft')),dy=+(keys.has('s')||keys.has('arrowdown'))-+(keys.has('w')||keys.has('arrowup'));p.x+=dx*155*p.speed/85*dt;p.y+=dy*90*dt;if(dx||dy)p.action='walk';for(const [key,kind]of [['j','punch'],['k','kick'],['l','suplex'],['g','press'],['t','toss'],['u','submission'],['n','pin'],['i','finisher'],['h','weapon'],['q','taunt']] as [string,Action][]){if(keys.has(key)){attack(s,0,kind);break;}}}
s.ai-=dt;if(!s.hold&&e.cooldown===0&&e.down===0){if(s.mode!=='ring'&&!e.weapon&&s.pickups.some(w=>!w.taken&&distance(e,w)<86))pickupWeapon(s,1);if(distance(e,p)>100){e.action='walk';e.x+=Math.sign(p.x-e.x)*100*e.speed/80*dt;e.y+=Math.sign(p.y-e.y)*62*dt;}else if(s.ai<=0){if(p.down>0)attack(s,1,s.mode==='backstage'?(e.weapon?'weapon':'submission'):p.hp<35?'pin':'submission');else if(e.energy>=100)attack(s,1,'finisher');else if(random()<.18){e.action='block';e.anim=.65;e.cooldown=.65;}else if(e.weapon)attack(s,1,'weapon');else attack(s,1,(e.id===1?['punch','press','toss','suplex']:['punch','kick','toss','suplex'] as Action[])[Math.floor(random()*4)] as Action);s.ai=.65+random()*.65;}}
if(!s.hold&&p.down===0&&e.down===0){const dx=e.x-p.x,dy=e.y-p.y;if(Math.abs(dx)<78&&Math.abs(dy)<35){const shift=(78-Math.abs(dx))/2,sign=dx>=0?1:-1;p.x-=shift*sign;e.x+=shift*sign;}}
}for(const f of s.fighters){f.x=Math.max(170,Math.min(870,f.x));f.y=Math.max(325,Math.min(445,f.y));}if(s.time<=0&&s.phase==='fight')finish(s,p.hp===e.hp?null:p.hp>e.hp?0:1,'TIME LIMIT');}
