'use client';
import {useEffect,useRef,useState} from 'react';
import {attack,createMatch,step,escapeHold,pickupWeapon,skipEntrance,newProfile,readProfile,buyUpgrade,roster as R,type Action,type Match,type Mode,type Upgrades,type Profile} from './engine';
import {render} from './renderer';
import FighterPortrait from './fighter-portrait';
import {ATLAS_URL} from './fighter-art';
import {ArenaAudio} from './arena-audio';
import ControlDeck from './control-deck';
import {canvasPoint,targetFromClick,steerMouse,type MouseTarget} from './mouse-controls';
const controls=[['W A S D','MOVE'],['J','PUNCH'],['K','KICK'],['L','SUPLEX'],['G','CHYNA PRESS'],['T','POWER TOSS'],['U','SUBMIT'],['N','PIN'],['SPACE','BLOCK'],['I','FINISHER'],['F','PICK UP'],['H','WEAPON'],['E','ESCAPE'],['Q','TAUNT'],['B','SNEAK ATTACK']];
const modes:{id:Mode,name:string,detail:string}[]=[{id:'ring',name:'MAIN EVENT',detail:'Pin fall or submission · Entrances'},{id:'extreme',name:'EXTREME RULES',detail:'Weapons legal · Breakable table'},{id:'backstage',name:'BACKSTAGE ASSAULT',detail:'Loading bay brawl · KO or tap-out'}];
const KEY='queens-ring-career-v1';
export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null),keys=useRef(new Set<string>()),game=useRef(createMatch()),atlas=useRef<HTMLImageElement|null>(null),career=useRef(newProfile());
 const pointerKeys=useRef(new Set<string>()),mouseTarget=useRef<MouseTarget|null>(null),blockLatch=useRef(false),rightBlock=useRef(false);
 const [blocked,Blocked]=useState(false),[voice,Voice]=useState(true);const voiceRef=useRef(true);
 const [sel,S]=useState(0),[opp,O]=useState(1),[mode,Mode]=useState<Mode>('ring'),[phase,P]=useState<Match['phase']>('select'),[ready,Ready]=useState(false),[assetError,AssetError]=useState(false),[training,Training]=useState(false),[entrances,Entrances]=useState(true),[profile,ProfileState]=useState<Profile>(newProfile),[storageError,StorageError]=useState(false),[reward,Reward]=useState(0);
 const [hud,H]=useState({hp:100,ehp:100,en:0,stamina:100,time:180,msg:'',hold:'',count:0,escape:0,trapped:false,weapon:'',durability:0}),[sound,SS]=useState(true);const director=useRef<ArenaAudio|null>(null),snd=useRef(true);
 function clearInput(){keys.current.clear();pointerKeys.current.clear();mouseTarget.current=null;rightBlock.current=false;blockLatch.current=false;Blocked(false);}
 function clickAction(key:string){if(game.current.phase!=='fight')return;mouseTarget.current=null;if(key===' '){blockLatch.current=!blockLatch.current;Blocked(blockLatch.current);return;}if(key==='e'){escapeHold(game.current,0);return;}if(key==='f'){pickupWeapon(game.current,0);return;}blockLatch.current=false;Blocked(false);if(game.current.fighters[0].action==='block')game.current.fighters[0].action='idle';const map:Record<string,Action>={j:'punch',k:'kick',l:'suplex',g:'press',t:'toss',u:'submission',n:'pin',i:'finisher',h:'weapon',q:'taunt',b:'ambush'};if(map[key])attack(game.current,0,map[key]);}
 function moveButton(key:string,e:React.PointerEvent<HTMLButtonElement>){if(e.button!==0||game.current.phase!=='fight')return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);mouseTarget.current=null;pointerKeys.current.add(key);}
 function canvasDown(e:React.PointerEvent<HTMLCanvasElement>){if(game.current.phase!=='fight')return;e.preventDefault();e.currentTarget.focus();e.currentTarget.setPointerCapture(e.pointerId);if(e.button===2){rightBlock.current=true;Blocked(true);mouseTarget.current=null;return;}if(e.button!==0)return;const point=canvasPoint(e.clientX,e.clientY,e.currentTarget.getBoundingClientRect());blockLatch.current=false;Blocked(false);mouseTarget.current=targetFromClick(game.current,point.x,point.y);}
 function canvasRelease(){rightBlock.current=false;Blocked(blockLatch.current);}
 function save(p:Profile){career.current=p;ProfileState(p);try{localStorage.setItem(KEY,JSON.stringify(p));StorageError(false);}catch{StorageError(true);}}
 function beep(f=130){director.current??=new ArenaAudio();director.current.setEnabled(snd.current);director.current.setVoice(voiceRef.current);director.current.activate();director.current.effect(f);}
 function start(chosen=mode){if(!ready)return;const next=chosen!=='backstage'&&entrances?'entrance':'fight';game.current=createMatch(sel,opp,next,chosen,career.current.upgrades[sel]);clearInput();P(next);Training(false);Reward(0);beep(500);}
 function pause(){const s=game.current;if(s.phase==='fight'||s.phase==='paused'){s.phase=s.phase==='fight'?'paused':'fight';P(s.phase);clearInput();}}
 function selectScreen(){game.current=createMatch(sel,opp,'select',mode,career.current.upgrades[sel]);P('select');clearInput();}
 function upgrade(kind:keyof Upgrades){if(phase!=='select')return;const next=buyUpgrade(career.current,sel,kind);if(next){save(next);beep(350);}}
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const p=readProfile(JSON.parse(raw));career.current=p;ProfileState(p);}}catch{StorageError(true);}const img=new Image();img.onload=()=>{atlas.current=img;Ready(true);};img.onerror=()=>AssetError(true);img.src=ATLAS_URL;return()=>{img.onload=null;img.onerror=null;};},[]);
 useEffect(()=>{if(phase==='select')game.current=createMatch(sel,opp,'select',mode,profile.upgrades[sel]);},[sel,opp,mode,phase,profile]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;const k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown',' ','j','k','l','g','t','u','n','i','h','f','q','e','b'].includes(k)&&game.current.phase==='fight')e.preventDefault();if(k==='escape'&&!e.repeat)pause();else if(k==='e'&&!e.repeat)escapeHold(game.current,0);else if(k==='f'&&!e.repeat)pickupWeapon(game.current,0);else keys.current.add(k);},up=(e:KeyboardEvent)=>{keys.current.delete(e.key.toLowerCase());},blur=()=>{clearInput();if(game.current.phase==='fight'){game.current.phase='paused';P('paused');}};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);let raf=0,last=0,ui=0,impact=0;
 const frame=(now:number)=>{const dt=Math.min((now-last)/1000||0,.035);last=now;const s=game.current,old=s.phase;const frameKeys=new Set([...keys.current,...pointerKeys.current]);if(blockLatch.current||rightBlock.current)frameKeys.add(' ');mouseTarget.current=steerMouse(s,mouseTarget.current,frameKeys,dt);step(s,dt,frameKeys);if(old!==s.phase)P(s.phase);if(s.phase==='over'&&!s.earned){s.earned=true;const won=s.winner===0,earned=won?3:1,p=career.current;save({...p,points:p.points+earned,wins:p.wins+(won?1:0),losses:p.losses+(s.winner===1?1:0)});Reward(earned);}director.current?.observe(s);const c=canvas.current?.getContext('2d');if(c){render(c,s,atlas.current,now/1000);const target=mouseTarget.current;if(target&&s.phase==='fight'){c.strokeStyle=target.action?'#f5b878':'#d6b8ff';c.lineWidth=2;c.beginPath();c.ellipse(target.x,target.y,17,8,0,0,Math.PI*2);c.stroke();c.fillStyle=c.strokeStyle;c.font='bold 10px Arial';c.textAlign='center';c.fillText(target.action?'APPROACH':'MOVE HERE',target.x,target.y+23);}}ui+=dt;if(ui>.07){const [p,e]=s.fighters;H({hp:p.hp/p.maxHp*100,ehp:e.hp/e.maxHp*100,en:p.energy,stamina:p.stamina,time:Math.ceil(s.time),msg:s.messageTime>0?s.message:'',hold:s.hold?.kind??'',count:s.hold?.kind==='pin'?Math.min(3,Math.floor(s.hold.time)+1):0,escape:s.hold?.escape??0,trapped:s.hold?.attacker===1,weapon:p.weapon??'',durability:p.durability});ui=0;}raf=requestAnimationFrame(frame);};raf=requestAnimationFrame(frame);return()=>{cancelAnimationFrame(raf);director.current?.dispose();director.current=null;window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);};},[]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'pause_match',description:'Pause the active wrestling match.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');if(game.current.phase!=='fight')throw new Error('No active match');game.current.phase='paused';clearInput();P('paused');return {status:'paused'};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 const level=profile.upgrades[sel],power=Math.round(R[sel].power*(1+level.power*.09)),health=(sel===1?115:100)+level.toughness*10;
 return <main>
 <header><a href="/" className="logo">Q<span>/</span>R</a><div className="brand">QUEENS OF THE RING<small>POWERHOUSE EDITION</small></div><div className="headright"><span>{profile.wins} W / {profile.losses} L</span><button onClick={()=>{SS(!sound);snd.current=!sound;director.current?.setEnabled(!sound);}}>SOUND {sound?'ON':'OFF'}</button><button onClick={()=>{Voice(!voice);voiceRef.current=!voice;director.current?.setVoice(!voice);}}>COMMENTARY {voice?'ON':'OFF'}</button></div></header>
 <div className="title"><div><small>FOUR ICONS. NO LIMITS.</small><h1>OWN THE RING<span>.</span></h1></div><div className="careerBadge"><b>{profile.points}</b><span>TRAINING POINTS</span><button disabled={phase!=='select'} onClick={()=>Training(!training)}>{training?'CLOSE TRAINING':'UPGRADE FIGHTER'} ↗</button></div></div>
 {phase==='select'&&<div className="modegrid" role="group" aria-label="Match type">{modes.map(m=><button key={m.id} className={mode===m.id?'mode active':'mode'} aria-pressed={mode===m.id} onClick={()=>Mode(m.id)}><strong>{m.name}</strong><small>{m.detail}</small></button>)}</div>}
 <section className="arena">
 {phase!=='entrance'&&<div className="hud"><div><small>YOU / {R[sel].title}</small><strong>{R[sel].name}</strong><div className="bar"><i style={{width:`${hud.hp}%`,background:R[sel].color}}/></div><div className="stamina"><i style={{width:`${hud.stamina}%`}}/></div></div><div className="timer"><small>{mode==='backstage'?'NO RULES':'MAIN EVENT'}</small><b>{Math.floor(hud.time/60)}:{String(hud.time%60).padStart(2,'0')}</b><small>{mode==='backstage'?'KO / TAP-OUT':'SINGLE MATCH'}</small></div><div className="right"><small>CPU / {R[opp].title}</small><strong>{R[opp].name}</strong><div className="bar"><i style={{width:`${hud.ehp}%`,background:R[opp].color}}/></div></div></div>}
 <canvas ref={canvas} tabIndex={0} onPointerDown={canvasDown} onPointerUp={canvasRelease} onPointerCancel={canvasRelease} onLostPointerCapture={canvasRelease} onContextMenu={e=>e.preventDefault()} width={1040} height={560} aria-label={mode==='backstage'?'Backstage wrestling brawl':'Wrestling ring and entrances'}/>
 <div className="message" aria-live="polite">{phase==='fight'&&hud.msg}</div>
 {phase==='entrance'&&<button className="skipEntrance" onClick={()=>{skipEntrance(game.current);P('fight');}}>SKIP ENTRANCES →</button>}
 {hud.hold&&phase==='fight'&&<div className="holdhud">{hud.count>0&&<b className="count">{hud.count}</b>}{['submission','pin'].includes(hud.hold)&&<><span>{hud.trapped?'TAP E REPEATEDLY TO ESCAPE':'KEEP THE HOLD'}</span><div className="escape"><i style={{width:`${hud.escape*100}%`}}/></div>{hud.trapped&&<button onClick={()=>escapeHold(game.current,0)}>BREAK FREE · E</button>}</>}</div>}
 {(!ready||['paused','over'].includes(phase))&&<div className="overlay"><small>{!ready?'FIGHTER ASSETS':phase==='paused'?'TAKE A BREATHER':'MATCH COMPLETE'}</small><h2>{!ready?(assetError?'ARTWORK COULD NOT LOAD':'LOADING FIGHTERS…'):phase==='paused'?'PAUSED':game.current.message.split(' · ')[0]}</h2>{phase==='over'&&<><p>{game.current.message.split(' · ')[1]}</p><span className="reward">+{reward} TRAINING POINTS</span></>}{ready&&<><button className="primary" onClick={phase==='paused'?pause:()=>start()}>{phase==='paused'?'RESUME MATCH':'REMATCH'} →</button><button onClick={selectScreen}>MATCH SETUP & UPGRADES</button></>}{assetError&&<button onClick={()=>window.location.reload()}>RETRY</button>}</div>}
 <div className="arenafoot"><span>● {phase==='select'?'CHOOSE YOUR MATCHUP':phase==='fight'?'MATCH LIVE':phase==='entrance'?'SUPERSTAR ENTRANCE':phase==='paused'?'PAUSED':'FINAL RESULT'}</span><div className="meter">FINISHER <div><i style={{width:`${hud.en}%`}}/></div><b>{hud.en>=100?'READY — I':`${Math.floor(hud.en)}%`}</b></div>{phase==='fight'&&<button onClick={pause}>Ⅱ PAUSE</button>}</div>
 </section>
 {phase==='fight'&&<ControlDeck onAction={clickAction} onMove={moveButton} onRelease={key=>pointerKeys.current.delete(key)} blocked={blocked} disabled={false} finisherReady={hud.en>=100} chyna={sel===1} weapons={mode!=='ring'} backstage={mode==='backstage'} trapped={hud.trapped&&['pin','submission'].includes(hud.hold)}/>}
 {phase==='fight'&&mode!=='ring'&&<div className="weaponstatus"><span>{hud.weapon?`${hud.weapon.toUpperCase()} EQUIPPED · ${hud.durability} HITS LEFT`:'WEAPONS ON THE FLOOR'}</span><b>F pick up / drop · H swing · T toss into the table</b></div>}
 {training&&phase==='select'&&<section className="training"><div><span className="eyebrow">TRAINING CENTER</span><h2>{R[sel].name} / POWER UP</h2><p>Power {power} · Health {health} · Speed {Math.round(R[sel].speed*(1+level.speed*.06))}</p><small>Win +3 points · Loss or draw +1 point · Saved on this device</small></div><div className="upgradegrid">{(['power','toughness','speed'] as (keyof Upgrades)[]).map(kind=><div className="upgrade" key={kind}><strong>{kind.toUpperCase()} <span>{level[kind]}/5</span></strong><p>{kind==='power'?'+9% base damage per level':kind==='toughness'?'+10 maximum health per level':'+6% base speed per level'}</p><button disabled={level[kind]>=5||profile.points<level[kind]+1} onClick={()=>upgrade(kind)}>{level[kind]>=5?'MAX LEVEL':`UPGRADE · ${level[kind]+1} POINT${level[kind]>0?'S':''}`}</button></div>)}</div>{storageError&&<p role="status">Storage is unavailable. Upgrades will last for this session only.</p>}</section>}
 <section className="roster"><div className="sectiontitle"><h2>SELECT YOUR SUPERSTAR</h2><span>04 / FIGHTERS</span></div><div className="cards">{R.map((r,i)=><button key={r.name} className={`card ${sel===i?'selected':''}`} style={{'--accent':r.color} as React.CSSProperties} disabled={phase!=='select'} aria-pressed={sel===i} onClick={()=>{S(i);if(opp===i)O((i+1)%4);}}><span className="num">0{i+1}</span><span className="tag">{sel===i?'● PLAYER 1':i===1?'POWERHOUSE':'SELECT'}</span><FighterPortrait id={i}/><div className="info"><small>{r.title}</small><h3>{r.name}</h3><div className="stats"><span>POWER <b>{Math.round(r.power*(1+profile.upgrades[i].power*.09))}</b></span><span>SPEED <b>{Math.round(r.speed*(1+profile.upgrades[i].speed*.06))}</b></span></div><p>{i===1?'GORILLA PRESS + PEDIGREE':r.finisher}</p></div></button>)}</div>
 {phase==='select'&&<div className="setup"><label>YOUR OPPONENT<select value={opp} onChange={e=>O(Number(e.target.value))}>{R.map((r,i)=>i!==sel&&<option value={i} key={i}>{r.name}</option>)}</select></label><div><p>{mode==='backstage'?'Ambush your rival in the loading bay.':'Wear them down. Slam. Pin for three.'}<br/><small>{mode==='backstage'?'Weapons, wall impacts and submissions.':'Chyna: G for Gorilla Press · I for Pedigree.'}</small></p>{mode!=='backstage'&&<label className="entranceCheck"><input type="checkbox" checked={entrances} onChange={e=>Entrances(e.target.checked)}/> PLAY RING ENTRANCES</label>}</div><button className="primary" onClick={()=>start()} disabled={!ready}>{mode==='backstage'?'START BACKSTAGE ASSAULT':'ENTER THE RING'} →</button></div>}
 </section>
 <section className="controls"><span>MOVE LIST</span>{controls.map(([k,v])=><div key={k}><kbd>{k}</kbd><small>{v}</small></div>)}</section>
 <p className="movehint">Mouse: click the floor to move, click your rival to attack, hold right-click to block. On-screen buttons work with clicks or touch. G: Chyna’s overhead press · T: grapple and throw · F/H: weapons in Extreme Rules or backstage · Q: taunt for momentum. Tap E to break a hold. The thin green bar is stamina.</p>
 <footer><span>Q/R · POWERHOUSE EDITION</span><span>Unofficial 2D fan game · AI-rendered characters</span></footer>
 </main>;
}
