'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import styles from '../3d-sandbox/sandbox.module.css';
import { BackstageRuntime, type BackstageSnapshot } from '../../game3d/backstage/runtime';
export default function BackstagePage() { const canvas = useRef<HTMLCanvasElement>(null); const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading'); const [snapshot, setSnapshot] = useState<BackstageSnapshot>({ x: 0, z: -12, yaw: 0, zone: 'MAIN_CORRIDOR', prompt: '', interaction: '', fps: 0, loaded: false });
  useEffect(() => { const surface = canvas.current; if (!surface) return; const runtime = new BackstageRuntime(surface, setSnapshot, () => setStatus('ready'), message => { setStatus('error'); setSnapshot(s => ({ ...s, zone: message })); }); return () => runtime.dispose(); }, []);
  return <main className={styles.shell}><div className={styles.topbar}><Link prefetch={false} href="/3d-match" className={styles.brand}>Q/R <span>RING LAB</span></Link><Link prefetch={false} href="/">← Main game</Link></div><div className={styles.title}><div><p>PHASE 07 / EXPLORABLE BACKSTAGE</p><h1>Behind the curtain.</h1></div><span className={styles.badge}>BACKSTAGE HUB</span></div><div className={styles.workspace}><div className={styles.viewport}><canvas ref={canvas} tabIndex={0} aria-label="3D backstage corridor with locker rooms and arena access" /><div className={styles.sceneLabel}><i />{status === 'ready' ? 'LIVE BACKSTAGE' : status === 'loading' ? 'LOADING BACKSTAGE' : 'BACKSTAGE LOAD FAILED'}<span>{snapshot.zone}</span></div><div className={styles.sceneFooter}><span>{snapshot.prompt || 'WASD TO EXPLORE'}</span><span>{snapshot.interaction ? `INTERACTED · ${snapshot.interaction}` : 'PRESS E NEAR ANCHOR'}</span></div></div><aside className={styles.sidebar}><p className={styles.eyebrow}>CONNECTED 3D HUB</p><h2>Explore every room.</h2><p>Walk the corridor with the shared third-person controller. Doors and future interaction anchors are physically placed in the world.</p><dl className={styles.debug}><div><dt>Zone</dt><dd data-testid="backstage-zone">{snapshot.zone}</dd></div><div><dt>Position</dt><dd data-testid="backstage-position">{snapshot.x.toFixed(2)} / {snapshot.z.toFixed(2)}</dd></div><div><dt>Prompt</dt><dd data-testid="backstage-prompt">{snapshot.prompt || '—'}</dd></div><div><dt>Interaction</dt><dd data-testid="backstage-interaction">{snapshot.interaction || '—'}</dd></div><div><dt>FPS</dt><dd>{snapshot.fps.toFixed(0)}</dd></div><div><dt>Loaded</dt><dd>{snapshot.loaded ? 'YES' : 'LOADING'}</dd></div></dl><p className={styles.note}>Areas: Rhea, Chyna, Charlotte and Bianca locker rooms · interview area · manager office · loading bay · arena access.</p></aside></div><p className={styles.bottom}>Phase 7 supplies environment, navigation, collision boundaries and interaction anchors. Interviews and manager behavior remain future systems.</p></main>;
}
