import type { RheaSceneDefinition, SceneName } from './types.ts';

const scene = (definition: RheaSceneDefinition): RheaSceneDefinition => Object.freeze({
  ...definition,
  allowedFramings: Object.freeze([...definition.allowedFramings]),
  allowedPoses: Object.freeze([...definition.allowedPoses]),
  allowedGestures: Object.freeze([...definition.allowedGestures]),
  allowedCameraStates: Object.freeze([...definition.allowedCameraStates]),
  safeTextArea: Object.freeze({ ...definition.safeTextArea }),
});

export const RHEA_SCENES: Readonly<Record<SceneName, RheaSceneDefinition>> = Object.freeze({
  INTERVIEW: scene({
    name: 'INTERVIEW',
    label: 'THE INTERVIEW',
    eyebrow: 'CONTROLLED INTERVIEW / 01',
    prompt: 'Say it to her face.',
    description: 'A controlled split composition built for direct questions and measured speaking segments.',
    background: 'CONTROLLED_STUDIO',
    container: 'INTERVIEW_SPLIT',
    defaultFraming: 'MEDIUM',
    allowedFramings: ['CLOSE', 'MEDIUM'],
    defaultPose: 'INTERVIEWER',
    allowedPoses: ['INTERVIEWER', 'PROMO_FRONT', 'CAMERA_STARE'],
    defaultGesture: 'IDLE',
    allowedGestures: ['IDLE', 'ARMS_RELAXED', 'LEAN_FORWARD', 'HEAD_TILT_EMPHASIS'],
    defaultCamera: 'STATIC_MEDIUM',
    allowedCameraStates: ['STATIC_MEDIUM', 'CLOSE_PROMO', 'SLOW_PUSH_IN', 'INTERVIEWER_ANGLE', 'CAMERA_STARE', 'FINAL_HOLD'],
    safeTextArea: { placement: 'RIGHT_PANEL', maxWidthPercent: 39, insetPercent: 3 },
  }),
  BACKSTAGE: scene({
    name: 'BACKSTAGE',
    label: 'BACKSTAGE',
    eyebrow: 'BACKSTAGE PROMO / 02',
    prompt: 'No crowd. No excuses.',
    description: 'A closer, more intimate promo shell with stable medium framing and restrained practical light.',
    background: 'INTIMATE_BACKSTAGE',
    container: 'BACKSTAGE_PROMO',
    defaultFraming: 'MEDIUM',
    allowedFramings: ['CLOSE', 'MEDIUM'],
    defaultPose: 'PROMO_FRONT',
    allowedPoses: ['NEUTRAL_STAND', 'PROMO_FRONT', 'THREE_QUARTER'],
    defaultGesture: 'IDLE',
    allowedGestures: ['IDLE', 'ARMS_RELAXED', 'CHEST_EMPHASIS', 'LEAN_FORWARD', 'HEAD_TILT_EMPHASIS'],
    defaultCamera: 'STATIC_MEDIUM',
    allowedCameraStates: ['STATIC_MEDIUM', 'CLOSE_PROMO', 'SLOW_PUSH_IN', 'SLOW_PULL_OUT', 'INTERVIEWER_ANGLE', 'CAMERA_STARE', 'FINAL_HOLD'],
    safeTextArea: { placement: 'LOWER_RIGHT', maxWidthPercent: 40, insetPercent: 4 },
  }),
  RING_ARENA: scene({
    name: 'RING_ARENA',
    label: 'RING / ARENA',
    eyebrow: 'ARENA PRESENTATION / 03',
    prompt: 'Own the spotlight.',
    description: 'A performance-oriented shell with safe medium and full-body presentation space.',
    background: 'ARENA_LIGHTS',
    container: 'RING_PRESENTATION',
    defaultFraming: 'FULL',
    allowedFramings: ['MEDIUM', 'FULL'],
    defaultPose: 'POWER_STANCE',
    allowedPoses: ['PROMO_FRONT', 'CAMERA_STARE', 'POWER_STANCE'],
    defaultGesture: 'IDLE',
    allowedGestures: ['IDLE', 'ARMS_RELAXED', 'CHEST_EMPHASIS', 'LEAN_FORWARD'],
    defaultCamera: 'STATIC_MEDIUM',
    allowedCameraStates: ['STATIC_MEDIUM', 'STATIC_FULL', 'CLOSE_PROMO', 'SLOW_PUSH_IN', 'SLOW_PULL_OUT', 'INTERVIEWER_ANGLE', 'CAMERA_STARE', 'FINAL_HOLD'],
    safeTextArea: { placement: 'RINGSIDE_RIGHT', maxWidthPercent: 36, insetPercent: 3 },
  }),
  PRESS_CONFERENCE: scene({
    name: 'PRESS_CONFERENCE',
    label: 'PRESS CONFERENCE',
    eyebrow: 'MEDIA AVAILABILITY / 04',
    prompt: 'One statement. Every camera.',
    description: 'A controlled camera-facing media setup with restrained movement and a clean press-wall composition.',
    background: 'PRESS_MEDIA_WALL',
    container: 'PRESS_DAIS',
    defaultFraming: 'MEDIUM',
    allowedFramings: ['CLOSE', 'MEDIUM'],
    defaultPose: 'CAMERA_STARE',
    allowedPoses: ['INTERVIEWER', 'PROMO_FRONT', 'CAMERA_STARE'],
    defaultGesture: 'IDLE',
    allowedGestures: ['IDLE', 'ARMS_RELAXED', 'HEAD_TILT_EMPHASIS'],
    defaultCamera: 'STATIC_MEDIUM',
    allowedCameraStates: ['STATIC_MEDIUM', 'CLOSE_PROMO', 'SLOW_PUSH_IN', 'INTERVIEWER_ANGLE', 'CAMERA_STARE', 'FINAL_HOLD'],
    safeTextArea: { placement: 'PRESS_RIGHT', maxWidthPercent: 38, insetPercent: 3 },
  }),
});
