'use client';
/* oxlint-disable */
import { useEffect, useMemo, useRef, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import styles from './promo.module.css';

const refs = { neutral: '/character-references/rhea/expression-neutral.png', smirk: '/character-references/rhea/expression-confident-smirk.png', angry: '/character-references/rhea/expression-aggressive-intimidating.png', threeQuarter: '/character-references/rhea/face-3quarter.png' } as const;
type Tone = 'AUTO' | 'CONFIDENT' | 'COLD' | 'MOCKING' | 'ANGRY' | 'INTIMIDATING' | 'SMIRKING';
const sample = "You really think you're ready for me? Then prove it.";
function beatFor(sentence: string, tone: Tone) { const lower = sentence.toLowerCase(); const expression = tone === 'ANGRY' || tone === 'INTIMIDATING' || lower.includes('prove') ? 'angry' : tone === 'SMIRKING' || lower.includes('?') ? 'smirk' : 'neutral'; return { sentence, expression, camera: lower.includes('prove') ? 'close' : lower.includes('?') ? 'medium' : 'hero' }; }

export default function PromoRhea() {
  const [text, setText] = useState(sample), [tone, setTone] = useState<Tone>('AUTO'), [speaking, setSpeaking] = useState(false), [done, setDone] = useState(false), [camera, setCamera] = useState('wide'), [expression, setExpression] = useState<'neutral'|'smirk'|'angry'>('neutral'), [subtitle, setSubtitle] = useState(''), [gaze, setGaze] = useState('interviewer'), [debug, setDebug] = useState(false);
  const [mouth, setMouth] = useState('REST'); const [blink, setBlink] = useState(false); const [beat, setBeat] = useState(0); const utterance = useRef<SpeechSynthesisUtterance | undefined>(undefined); const timers = useRef<number[]>([]);
  const sentences = useMemo(() => text.split(/(?<=[.!?])\s+/).filter(Boolean), [text]);
  const stop = () => { window.speechSynthesis?.cancel(); timers.current.forEach(window.clearTimeout); timers.current = []; setSpeaking(false); setMouth('REST'); setSubtitle(''); setDone(false); setCamera('wide'); setExpression('neutral'); setBeat(0); };
  const deliver = () => { stop(); if (!text.trim()) return; setSpeaking(true); setCamera('medium'); const chunks = sentences.map((sentence, index) => ({ ...beatFor(sentence, tone), index })); chunks.forEach((item, index) => { const delay = chunks.slice(0, index).reduce((sum, prior) => sum + Math.max(900, prior.sentence.length * 48), 0); timers.current.push(window.setTimeout(() => { setSubtitle(item.sentence); setExpression(item.expression as 'neutral'|'smirk'|'angry'); setCamera(item.camera); setGaze(item.camera === 'close' ? 'camera' : 'interviewer'); setBeat(index); }, delay)); }); const u = new SpeechSynthesisUtterance(text); u.rate = .92; u.pitch = .72; u.volume = 1; u.onstart = () => setSpeaking(true); u.onboundary = () => { setMouth(Math.random() > .55 ? 'ROUND_O' : 'OPEN_AE'); window.setTimeout(() => setMouth('REST'), 120); }; u.onend = () => { setMouth('REST'); setSubtitle(''); setSpeaking(false); setDone(true); setCamera('close'); setExpression(tone === 'COLD' || tone === 'INTIMIDATING' ? 'angry' : 'smirk'); setGaze('camera'); }; u.onerror = () => { setMouth('REST'); setSpeaking(false); }; utterance.current = u; window.speechSynthesis.speak(u); };
  useEffect(() => { const loop = () => { setBlink(true); window.setTimeout(() => setBlink(false), 130); }; const id = window.setInterval(loop, 3200 + Math.random() * 1800); return () => window.clearInterval(id); }, []);
  useEffect(() => () => stop(), []);
  const portrait = expression === 'angry' ? refs.angry : expression === 'smirk' ? refs.smirk : refs.neutral;
  return <main className={`${styles.shell} ${styles[camera]}`}><header><a href="/">Q/R <span>PROMO QUEENS</span></a><button onClick={() => setDebug(value => !value)}>DEV REVIEW</button></header><section className={styles.stage}><div className={styles.set}><div className={styles.brand}>PROMO<br/><b>QUEENS</b></div><div className={styles.mic}>●</div><div className={styles.interviewer}><span>INTERVIEWER</span></div><div className={`${styles.character} ${speaking ? styles.talking : ''} ${done ? styles.final : ''}`}><img className={styles.portrait} src={portrait} alt="Rhea-inspired expressive promo portrait"/><div className={`${styles.eyelid} ${blink ? styles.blink : ''}`} /><div className={`${styles.mouth} ${styles[mouth]}`} aria-hidden="true"/><div className={`${styles.gaze} ${styles[gaze]}`} /></div><div className={styles.cameraLabel}>{camera.toUpperCase()} · {gaze.toUpperCase()}</div></div><aside className={styles.panel}><p className={styles.kicker}>RHEA / BACKSTAGE INTERVIEW</p><h1>Say it to her face.</h1><p className={styles.question}>“What&apos;s next for you?”</p><label>YOUR PROMO<textarea value={text} onChange={event => setText(event.target.value)} maxLength={420} /></label><label>TONE<select value={tone} onChange={event => setTone(event.target.value as Tone)}>{(['AUTO','CONFIDENT','COLD','MOCKING','ANGRY','INTIMIDATING','SMIRKING'] as Tone[]).map(item => <option key={item}>{item}</option>)}</select></label><div className={styles.actions}><button className={styles.primary} onClick={deliver}>DELIVER PROMO</button><button onClick={stop}>STOP</button><button onClick={() => { setText(sample); deliver(); }}>REPLAY</button></div>{subtitle && <div className={styles.subtitle}>{subtitle}</div>}{done && <div className={styles.complete}>PROMO COMPLETE · HOLDING THE STARE</div>}<div className={styles.status}><span>{speaking ? `SPEAKING · ${mouth}` : done ? 'FINAL HOLD' : 'READY'}</span><span>{Math.round((beat + 1) / Math.max(1, sentences.length) * 100)}%</span></div>{debug && <div className={styles.debug}>Expression: {expression}<br/>Camera: {camera}<br/>Gaze: {gaze}<br/>Sentences: {sentences.length}<br/>Synthetic browser voice · exact text preserved</div>}</aside></section></main>;
}
