'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import styles from '../3d-sandbox/sandbox.module.css';
import { EntranceRuntime, type EntranceSnapshot } from '../../game3d/entrance/runtime';
import type { EntranceIdentity } from '../../game3d/entrance/system';

const identities: EntranceIdentity[] = ['RHEA', 'CHYNA', 'CHARLOTTE', 'BIANCA'];
export default function EntrancePage() { const canvas = useRef<HTMLCanvasElement>(null); const [identity, setIdentity] = useState<EntranceIdentity>('RHEA'); const [snapshot, setSnapshot] = useState<EntranceSnapshot>({ state: 'NOT_STARTED', identity: 'RHEA', time: 0, event: '', camera: '', loaded: false, fps: 0 }); const runtime = useRef<EntranceRuntime | undefined>(undefined);
  useEffect(() => { const surface = canvas.current; if (!surface) return; const instance = new EntranceRuntime(surface, identity, setSnapshot, () => undefined, message => setSnapshot(s => ({ ...s, state: `ERROR: ${message}` }))); runtime.current = instance; return () => instance.dispose(); }, [identity]);
  return <main className={styles.shell}><div className={styles.topbar}><Link prefetch={false} href="/3d-match" className={styles.brand}>Q/R <span>RING LAB</span></Link><Link prefetch={false} href="/">← Main game</Link></div><div className={styles.title}><div><p>PHASE 06 / INDIVIDUAL ENTRANCES</p><h1>Make an entrance.</h1></div><span className={styles.badge}>CINEMATIC TIMELINE</span></div><div className={styles.workspace}><div className={styles.viewport}><canvas ref={canvas} aria-label="3D wrestling entrance stage and ramp" /><div className={styles.sceneLabel}><i />LIVE ENTRANCE SCENE<span>{snapshot.identity} · {snapshot.state}</span></div><div className={styles.sceneFooter}><span>{snapshot.event || 'STAGE READY'}</span><span>{snapshot.camera || 'stage-hero'}</span></div></div><aside className={styles.sidebar}><p className={styles.eyebrow}>DATA-DRIVEN PRESENTATION</p><h2>Four identities. Four rhythms.</h2><p>Temporary rigged humanoids follow distinct stage, ramp, ringside, entry and pose timelines.</p><div className="modegrid">{identities.map(item => <button className={item === identity ? 'mode active' : 'mode'} key={item} onClick={() => setIdentity(item)}>{item}<small>{item === 'RHEA' ? 'intimidating' : item === 'CHYNA' ? 'powerhouse' : item === 'CHARLOTTE' ? 'grand' : 'athletic'}</small></button>)}</div><button className="primary" onClick={() => runtime.current?.skip()}>SKIP ENTRANCE →</button>{(snapshot.state === 'COMPLETE' || snapshot.state === 'SKIPPED') && <Link prefetch={false} href="/3d-match">Continue to match</Link>}<dl className={styles.debug}><div><dt>State / time</dt><dd>{snapshot.state} · {snapshot.time.toFixed(1)}s</dd></div><div><dt>Camera cue</dt><dd>{snapshot.camera || '—'}</dd></div><div><dt>Presentation</dt><dd>{snapshot.event || '—'}</dd></div><div><dt>FPS</dt><dd>{snapshot.fps.toFixed(0)}</dd></div><div><dt>Loaded</dt><dd>{snapshot.loaded ? 'YES' : 'LOADING'}</dd></div></dl></aside></div><p className={styles.bottom}>Temporary locomotion clips; final entrance poses remain unavailable.</p></main>;
}
